### ISSUE TITLE
Remove output from view

### ISSUE THREAD

**Issue by waldifubu** [rauwebieten/twig-stringy-extension#1]
Hello,

I tried to add the extension to Symfony.
Here comes my problem:

In line 98 is:
`print '- ' . $filtername . PHP_EOL;`

The result is, every time the methods are loaded, they will be outputted.
Could you please remove this line or explain to me the sense of this line?

And a little notice:
TwigExtension must now extend from "Twig\Extension\AbstractExtension;" (Twig >2.7)

Thanks in advance.
Kind regards,

Waldi

**Comment by rauwebieten** [comment]
Thanks!
Fixed in 3.2
