### ISSUE TITLE
Support for Twig 3.0

### ISSUE THREAD

**Issue by waldifubu** [rauwebieten/twig-stringy-extension#3]
Hello,

thx for merge my request. I have a another issue:

Some of my libraries need Twig 3.0 and above. No problem, this library is compatible.
The only issue is in composer.json:
 "twig/twig": "^2.0",

Why we don't change it to:

 "twig/twig": "^2.0 || ^3.0",
?

Unfortunately I don't know if it's a good idea or sth. will be crashed.
On the other side, my library and this extension are working together.

What is your opinion?

Kind regards
waldifubu

**Comment by rauwebieten** [comment]
I will do some tests with Twig 3 and modify composer requirements

**Comment by rauwebieten** [comment]
added in v3.3
